/**
 * About Tab Component
 * 
 * Comprehensive information about Trustie, how it works, 
 * the trust paradigm shift, and why verification matters.
 */

import React, { useState } from 'react'
import { Card, Button } from '@/components/ui'
import { 
  APP_NAME, 
  APP_VERSION, 
  APP_TAGLINE, 
  PROBLEMS_WE_SOLVE,
  TRUSTIE_PHILOSOPHY,
  SEARCH_ENGINE_RANKINGS,
  SPECIALTY_SEARCH_ENGINES,
} from '@/lib/constants'
import { cn } from '@/lib/utils'

type AboutSection = 'overview' | 'how-it-works' | 'why-trust' | 'sources' | 'faq'

const SECTIONS: { id: AboutSection; label: string; icon: string }[] = [
  { id: 'overview', label: 'Overview', icon: '📖' },
  { id: 'how-it-works', label: 'How It Works', icon: '⚙️' },
  { id: 'why-trust', label: 'Why Trust Matters', icon: '🛡️' },
  { id: 'sources', label: 'Our Sources', icon: '📚' },
  { id: 'faq', label: 'FAQ', icon: '❓' },
]

export function AboutTab() {
  const [activeSection, setActiveSection] = useState<AboutSection>('overview')
  
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold text-gray-100 mb-2">{APP_NAME}</h1>
        <p className="text-xl text-blue-400">{APP_TAGLINE}</p>
        <p className="text-gray-500 text-sm mt-2">Version {APP_VERSION}</p>
      </div>
      
      {/* Section Navigation */}
      <div className="flex flex-wrap justify-center gap-2 mb-6">
        {SECTIONS.map(({ id, label, icon }) => (
          <button
            key={id}
            onClick={() => setActiveSection(id)}
            className={cn(
              'px-4 py-2 rounded-lg text-sm transition-all',
              activeSection === id
                ? 'bg-blue-600 text-white'
                : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
            )}
          >
            {icon} {label}
          </button>
        ))}
      </div>
      
      {/* Section Content */}
      <div className="animate-fadeIn">
        {activeSection === 'overview' && <OverviewSection />}
        {activeSection === 'how-it-works' && <HowItWorksSection />}
        {activeSection === 'why-trust' && <WhyTrustSection />}
        {activeSection === 'sources' && <SourcesSection />}
        {activeSection === 'faq' && <FAQSection />}
      </div>
    </div>
  )
}

function OverviewSection() {
  return (
    <div className="space-y-6">
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">What is Trustie?</h2>
        <p className="text-gray-300 leading-relaxed mb-4">
          Trustie is the trust layer for the AI era. We help you verify AI-generated 
          content against real, authoritative sources so you never have to blindly 
          trust what AI tells you.
        </p>
        <p className="text-gray-300 leading-relaxed">
          {TRUSTIE_PHILOSOPHY.mission}. Our approach: {TRUSTIE_PHILOSOPHY.approach}. 
          What makes us different: {TRUSTIE_PHILOSOPHY.differentiator}.
        </p>
      </Card>
      
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">Problems We Solve</h2>
        <div className="grid gap-4 md:grid-cols-2">
          {PROBLEMS_WE_SOLVE.map(({ problem, description, solution }) => (
            <div key={problem} className="p-4 bg-gray-900 rounded-lg">
              <h3 className="font-semibold text-red-400 mb-1">❌ {problem}</h3>
              <p className="text-gray-400 text-sm mb-2">{description}</p>
              <p className="text-emerald-400 text-sm">✓ {solution}</p>
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}

function HowItWorksSection() {
  return (
    <div className="space-y-6">
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">The Verification Process</h2>
        
        <div className="space-y-6">
          <Step 
            number={1}
            title="You Paste AI Output"
            description="Copy any text generated by ChatGPT, Claude, Gemini, or any other AI."
          />
          <Step 
            number={2}
            title="We Extract Claims"
            description="Our AI identifies every factual claim that can be verified. Opinions and predictions are flagged separately."
          />
          <Step 
            number={3}
            title="We Search Trusted Sources"
            description="Each claim is checked against .edu, .gov, peer-reviewed journals, and major news outlets."
          />
          <Step 
            number={4}
            title="You See the Evidence"
            description="Every claim is marked Verified, False, or Unconfirmed with the sources that support or refute it."
          />
        </div>
      </Card>
      
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">Search vs. Check</h2>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="p-4 bg-gray-900 rounded-lg">
            <h3 className="font-semibold text-blue-400 mb-2">🔍 Search</h3>
            <p className="text-gray-400 text-sm">
              Ask any question and get an answer verified by trusted sources. 
              Like Google, but with trust scores and source transparency.
            </p>
          </div>
          <div className="p-4 bg-gray-900 rounded-lg">
            <h3 className="font-semibold text-emerald-400 mb-2">✓ Check AI</h3>
            <p className="text-gray-400 text-sm">
              Paste AI-generated content and verify every claim. 
              Perfect for checking ChatGPT, Claude, or any AI output.
            </p>
          </div>
        </div>
      </Card>
    </div>
  )
}

function Step({ number, title, description }: { number: number; title: string; description: string }) {
  return (
    <div className="flex gap-4">
      <div className="flex-shrink-0 w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center font-bold">
        {number}
      </div>
      <div>
        <h3 className="font-semibold text-gray-100">{title}</h3>
        <p className="text-gray-400 text-sm">{description}</p>
      </div>
    </div>
  )
}

function WhyTrustSection() {
  return (
    <div className="space-y-6">
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">The Trust Paradigm Shift</h2>
        <p className="text-gray-300 leading-relaxed mb-4">
          We are living through the biggest shift in how humans find and trust information 
          since the invention of the search engine.
        </p>
        
        <div className="space-y-4">
          <div className="p-4 bg-gray-900 rounded-lg border-l-4 border-gray-500">
            <h3 className="font-semibold text-gray-300 mb-2">Traditional Search (Google Era)</h3>
            <ul className="text-gray-400 text-sm space-y-1">
              <li>• You search → Algorithm ranks pages → You click links → <strong>You evaluate sources</strong></li>
              <li>• Trust lives in the user</li>
              <li>• You see 10 blue links and decide what to believe</li>
            </ul>
          </div>
          
          <div className="p-4 bg-gray-900 rounded-lg border-l-4 border-amber-500">
            <h3 className="font-semibold text-amber-300 mb-2">AI Search (ChatGPT Era)</h3>
            <ul className="text-gray-400 text-sm space-y-1">
              <li>• You ask → AI synthesizes answer → <strong>You trust the AI</strong></li>
              <li>• Trust lives in the AI</li>
              <li>• You get 1 confident answer with no visible sources</li>
            </ul>
          </div>
          
          <div className="p-4 bg-gray-900 rounded-lg border-l-4 border-emerald-500">
            <h3 className="font-semibold text-emerald-300 mb-2">Verified AI (Trustie Era)</h3>
            <ul className="text-gray-400 text-sm space-y-1">
              <li>• AI generates → Trustie verifies → <strong>You see evidence</strong></li>
              <li>• Trust is earned through transparency</li>
              <li>• You get the answer AND the receipts</li>
            </ul>
          </div>
        </div>
      </Card>
      
      <Card className="bg-amber-900/20 border-amber-500/30">
        <h3 className="font-semibold text-amber-300 mb-3">⚠️ The Problem with AI Search</h3>
        <p className="text-gray-300 leading-relaxed">
          Safari searches declined for the first time ever in April 2025. Users are turning to AI. 
          But AI can hallucinate, fabricate citations, and confidently state false information. 
          Without verification, there is no way to know what is true.
        </p>
      </Card>
    </div>
  )
}

function SourcesSection() {
  return (
    <div className="space-y-6">
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">How We Rank Sources</h2>
        
        <div className="space-y-4">
          <div className="p-4 bg-emerald-900/30 rounded-lg border border-emerald-500/30">
            <h3 className="font-semibold text-emerald-300 mb-2">🏆 High Trust Sources</h3>
            <p className="text-gray-400 text-sm mb-2">
              These sources meet the highest standards for accuracy and reliability.
            </p>
            <div className="flex flex-wrap gap-2">
              {['.edu', '.gov', 'PubMed', 'Nature', 'Science Direct', 'Google Scholar', 
                'WHO', 'CDC', 'NIH', 'NASA', 'Britannica', 'Wolfram Alpha'].map(source => (
                <span key={source} className="px-2 py-1 bg-emerald-900/50 text-emerald-300 text-xs rounded">
                  {source}
                </span>
              ))}
            </div>
          </div>
          
          <div className="p-4 bg-amber-900/30 rounded-lg border border-amber-500/30">
            <h3 className="font-semibold text-amber-300 mb-2">⚖️ Medium Trust Sources</h3>
            <p className="text-gray-400 text-sm mb-2">
              Reliable but require cross-referencing for critical information.
            </p>
            <div className="flex flex-wrap gap-2">
              {['Wikipedia', 'Reuters', 'AP News', 'BBC', 'NPR', 'NYT', 'WSJ', 
                'The Guardian', 'Bloomberg', 'Snopes', 'Politifact'].map(source => (
                <span key={source} className="px-2 py-1 bg-amber-900/50 text-amber-300 text-xs rounded">
                  {source}
                </span>
              ))}
            </div>
          </div>
          
          <div className="p-4 bg-gray-900 rounded-lg border border-gray-700">
            <h3 className="font-semibold text-gray-400 mb-2">⚠️ Verify Manually</h3>
            <p className="text-gray-500 text-sm mb-2">
              Other sources may be accurate but require additional verification.
            </p>
            <p className="text-gray-500 text-xs">
              Includes: blogs, forums, social media, content aggregators, opinion pieces
            </p>
          </div>
        </div>
      </Card>
      
      <Card>
        <h2 className="text-xl font-bold text-gray-100 mb-4">Inspired by the Best</h2>
        <p className="text-gray-400 text-sm mb-4">
          Our verification approach combines lessons from the most reliable search systems:
        </p>
        <div className="space-y-3">
          {SPECIALTY_SEARCH_ENGINES.map(engine => (
            <div key={engine.name} className="flex items-center gap-3 text-sm">
              <span className="text-emerald-400">✓</span>
              <span className="text-gray-300 font-medium">{engine.name}</span>
              <span className="text-gray-500">— {engine.domain} ({engine.reliability})</span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}

function FAQSection() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  
  const faqs = [
    {
      q: 'Is Trustie free to use?',
      a: 'Yes! Trustie is currently free. We may add premium features in the future, but basic verification will always be available.',
    },
    {
      q: 'How accurate is Trustie?',
      a: 'We verify claims against the most authoritative sources available. However, no verification system is perfect. Always use critical thinking, especially for important decisions.',
    },
    {
      q: 'What AI tools can I check?',
      a: 'You can verify output from any AI including ChatGPT, Claude, Gemini, Perplexity, Copilot, Grok, and more.',
    },
    {
      q: 'Do you store my data?',
      a: 'We do not store the content you verify. Your searches and verifications are processed in real-time and not saved.',
    },
    {
      q: 'Why are some claims marked "Unconfirmed"?',
      a: 'Unconfirmed means we could not find sufficient evidence to verify or refute the claim. This does not mean it is false, just that it requires additional verification.',
    },
    {
      q: 'Can I use Trustie for academic work?',
      a: 'Yes! Trustie is great for checking AI-assisted research. However, always cite original sources, not Trustie, in your academic work.',
    },
    {
      q: 'How is Trustie different from other fact-checkers?',
      a: 'Traditional fact-checkers review specific viral claims manually. Trustie automatically verifies any AI-generated text in seconds using algorithmic source matching.',
    },
    {
      q: 'What about opinions and predictions?',
      a: 'We identify opinions and predictions separately from factual claims. Opinions cannot be verified as true or false, and predictions about the future are flagged appropriately.',
    },
  ]
  
  return (
    <div className="space-y-3">
      {faqs.map((faq, i) => (
        <Card 
          key={i}
          hoverable
          className="cursor-pointer"
          onClick={() => setOpenFaq(openFaq === i ? null : i)}
        >
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-gray-100">{faq.q}</h3>
            <span className="text-gray-400">{openFaq === i ? '−' : '+'}</span>
          </div>
          {openFaq === i && (
            <p className="text-gray-400 mt-3 text-sm">{faq.a}</p>
          )}
        </Card>
      ))}
    </div>
  )
}

export default AboutTab
